In [1]:
import pandas as pd

path ='Riktim_Testing/Line-level-Features/DHT_Algorithm_144_Features.csv'
df = pd.read_csv(path) #header=None
df.head()

att_1  att_2  att_3  att_4  att_5  att_6  att_7  att_8  att_9  att_10  ...  \
0    279     60     39     36     24     21     20     19     20      22  ...   
1    272     62     43     27     24     20     20     20     25      18  ...   
2    177     82     46     28     23     22     19     16     17      16  ...   
3    205     84     44     26     25     23     20     20     20      28  ...   
4    166     91     38     26     25     21     19     19     19      17  ...   

   att_136  att_137  att_138  att_139  att_140  att_141  att_142  att_143  \
0     3993     2419     3320     2660     2850     2591     2594     2444   
1     2687     2887     3494     2496     2591     2745     2384     2351   
2     3071     3717     3073     2835     3094     2499     2480     2483   
3     3818     2340     2372     2372     2370     2537     2526     2521   
4     2388     2561     2558     2543     3033     2928     2825     2530   

   att_144  class  
0     2546      A  
1     2411      A  
2     2548      A  
3     2418      A  
4     2424      A  

[5 rows x 145 columns]

In [2]:
# Import modules
import numpy as np
# import matplotlib.pyplot as plt
# from sklearn.datasets import load_iris,load_digits,load_breast_cancer,load_wine
# from sklearn import preprocessing

# Some more magic so that the notebook will reload external python modules;
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2

In [3]:
# # Load the iris dataset
# data = load_digits()

# # Store the features as X and the labels as y
# X = data.data
# y = data.target

In [4]:
df.columns

Index(['att_1', 'att_2', 'att_3', 'att_4', 'att_5', 'att_6', 'att_7', 'att_8',
       'att_9', 'att_10',
       ...
       'att_136', 'att_137', 'att_138', 'att_139', 'att_140', 'att_141',
       'att_142', 'att_143', 'att_144', 'class'],
      dtype='object', length=145)

In [5]:
print(df.shape)
#X=df.loc[:,df.columns != 'Classifier'].values
X=df.loc[:,df.columns != df.columns[-1]].values
print(type(X))
print(X.shape)
#y_label=df['Classifier'].values 
y_label =df.iloc[:,-1].values
#print(type(y_label))
#print(X[0])
print()
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(y_label)
print(le.classes_)
y=le.transform(y_label)
print(y[:10])

(3600, 145)
<class 'numpy.ndarray'>
(3600, 144)

['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L']
[0 0 0 0 0 0 0 0 0 0]


In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler #for normalization
sc = StandardScaler()
X = sc.fit_transform(X)
# from sklearn.preprocessing import MinMaxScaler
# scaler = MinMaxScaler(feature_range=(0, 1))
# X = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, shuffle=True)
# print(y_train)
# print(y_test)
#print(len(X_train), len(y_train), len(X_test), len(y_test))
# # X=X_train
# # y=y_train
print(set(y_train), set(y_test))
print(X.shape, y.shape,X_train.shape,X_test.shape,y_train.shape,y_test.shape)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11} {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11}
(3600, 144) (3600,) (2520, 144) (1080, 144) (2520,) (1080,)


In [7]:
n_inputs = X_train.shape[1]
n_hidden = X_train.shape[1]
n_classes = len(le.classes_)
#N = X_train.shape[0] # Number of samples

#print(N)
#hyperparameters
lr = 0.001
num_epoch = 310

In [8]:
import torch
import torch.nn as nn
import torch.nn.functional as F
#torch.manual_seed(1234)

In [9]:
#build model
class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(n_inputs, n_hidden)
        self.drop = nn.Dropout (p=0.4)
        self.fc2 = nn.Linear(n_hidden,n_classes )

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x=self.drop(x)
        x = self.fc2(x)
        return x
        
net = Net()

In [10]:
#choose optimizer and loss function
criterion = nn.CrossEntropyLoss()
#optimizer = torch.optim.SGD(net.parameters(), lr=0.001)
optimizer = torch.optim.Adam(net.parameters(), lr=lr)

#swap test and train
# X_train,X_test=X_test,X_train
# y_train,y_test =y_test,y_train

In [11]:
# #print(type(X_train[0]),type(X_test[0]),type(y_train[0]),type(y_test[0]))
# from sklearn.model_selection import KFold # import KFold
# kf = KFold(n_splits=5,shuffle=True, random_state=42)

In [12]:
# #train
# train_scores=[]
# test_scores=[]
# acc=0
# for k, (train, test) in enumerate(kf.split(X, y)):
#   X_train, X_test = X[train], X[test]
#   y_train, y_test = y[train], y[test]
#  # X_train = torch.tensor(X_train, dtype=torch.float)
#  # y_train = torch.tensor(y_train, dtype=torch.long)
#  # X_test = torch.tensor(X_test, dtype=torch.float)
#  # y_test = torch.tensor(y_test, dtype=torch.long)
#   net.train()
#   #print(X_train.shape, y_train.shape)
#   #train.sort()
#   #test.sort()
#   #print(train== test)
#   #print(train[:10])
#   #print(test[:10])
#   print(set(list(y_test)))
#   print(set(list(y_train)))
#   continue
#   for epoch in range(num_epoch):
#       #feedforward - backprop
#       optimizer.zero_grad()
#       out = net(X_train)
#       loss = criterion(out, y_train)
#       loss.backward()
#       optimizer.step()
#       acc = 100 * torch.sum(y_train==torch.max(out.data, 1)[1]).double() / len(y_train)
#       print ('Epoch [%d/%d] Loss: %.4f   Acc: %.4f' 
#                     %(epoch+1, num_epoch, loss.item(), acc.item()))
#   train_scores.append(acc)
#   print(X_test.shape, y_test.shape)
#   net.eval()
#   out = net(X_test)
#   _, predicted = torch.max(out.data, 1) 
#   test_scores.append((100 * torch.sum(y_test==predicted).double() / len(y_test)));
#   del net
#   net = Net()
#   criterion = nn.CrossEntropyLoss()
#   #optimizer = torch.optim.SGD(net.parameters(), lr=0.001)
#   optimizer = torch.optim.Adam(net.parameters(), lr=lr)

In [13]:
# out = net(X_train)
# _, predicted = torch.max(out.data, 1) 
# print((100 * torch.sum(y_train==predicted).double() / len(y_train)));

In [14]:
# print(train_scores)
# print(test_scores)

In [15]:

X_train = torch.tensor(X_train, dtype=torch.float)
y_train = torch.tensor(y_train, dtype=torch.long)
X_test = torch.tensor(X_test, dtype=torch.float)
y_test = torch.tensor(y_test, dtype=torch.long)
net.train()
#print(X_train.shape, y_train.shape)
for epoch in range(num_epoch):
    #feedforward - backprop
    optimizer.zero_grad()
    out = net(X_train)
    loss = criterion(out, y_train)
    loss.backward()
    optimizer.step()
    acc = 100 * torch.sum(y_train==torch.max(out.data, 1)[1]).double() / len(y_train)
    print ('Epoch [%d/%d] Loss: %.4f   Acc: %.4f' 
                  %(epoch+1, num_epoch, loss.item(), acc.item()))

Epoch [1/310] Loss: 2.5466   Acc: 7.2619
Epoch [2/310] Loss: 2.4555   Acc: 12.0238
Epoch [3/310] Loss: 2.3796   Acc: 18.0159
Epoch [4/310] Loss: 2.3168   Acc: 21.7063
Epoch [5/310] Loss: 2.2500   Acc: 25.7937
Epoch [6/310] Loss: 2.1928   Acc: 31.5476
Epoch [7/310] Loss: 2.1315   Acc: 33.6111
Epoch [8/310] Loss: 2.0842   Acc: 35.9127
Epoch [9/310] Loss: 2.0288   Acc: 37.7381
Epoch [10/310] Loss: 1.9867   Acc: 39.0079
Epoch [11/310] Loss: 1.9458   Acc: 41.5079
Epoch [12/310] Loss: 1.9005   Acc: 44.2460
Epoch [13/310] Loss: 1.8506   Acc: 44.4444
Epoch [14/310] Loss: 1.8166   Acc: 46.7857
Epoch [15/310] Loss: 1.7981   Acc: 46.3889
Epoch [16/310] Loss: 1.7472   Acc: 49.2460
Epoch [17/310] Loss: 1.7197   Acc: 49.8016
Epoch [18/310] Loss: 1.6837   Acc: 51.0317
Epoch [19/310] Loss: 1.6456   Acc: 52.3413
Epoch [20/310] Loss: 1.6241   Acc: 53.2937
Epoch [21/310] Loss: 1.5911   Acc: 54.6032
Epoch [22/310] Loss: 1.5535   Acc: 57.3016
Epoch [23/310] Loss: 1.5240   Acc: 57.8175
Epoch [24/310] Loss: 

Epoch [206/310] Loss: 0.1474   Acc: 96.7857
Epoch [207/310] Loss: 0.1551   Acc: 96.3492
Epoch [208/310] Loss: 0.1456   Acc: 97.0238
Epoch [209/310] Loss: 0.1479   Acc: 97.1032
Epoch [210/310] Loss: 0.1432   Acc: 97.3413
Epoch [211/310] Loss: 0.1443   Acc: 97.2222
Epoch [212/310] Loss: 0.1349   Acc: 97.7381
Epoch [213/310] Loss: 0.1474   Acc: 96.9841
Epoch [214/310] Loss: 0.1413   Acc: 97.5000
Epoch [215/310] Loss: 0.1376   Acc: 97.3810
Epoch [216/310] Loss: 0.1331   Acc: 97.5397
Epoch [217/310] Loss: 0.1408   Acc: 97.2619
Epoch [218/310] Loss: 0.1372   Acc: 97.4603
Epoch [219/310] Loss: 0.1337   Acc: 97.2222
Epoch [220/310] Loss: 0.1403   Acc: 97.2619
Epoch [221/310] Loss: 0.1362   Acc: 97.1825
Epoch [222/310] Loss: 0.1293   Acc: 97.5397
Epoch [223/310] Loss: 0.1356   Acc: 97.0238
Epoch [224/310] Loss: 0.1351   Acc: 97.1429
Epoch [225/310] Loss: 0.1318   Acc: 97.3810
Epoch [226/310] Loss: 0.1305   Acc: 97.5397
Epoch [227/310] Loss: 0.1230   Acc: 97.6190
Epoch [228/310] Loss: 0.1233   A

In [16]:
#X_test = torch.tensor(X_test, dtype=torch.float)
#y_test = torch.tensor(y_test, dtype=torch.long)
net.eval()
out = net(X_test)
_, predicted = torch.max(out.data, 1)
print(predicted[0:10])
#get accuration
print('Accuracy of the network %.4f %%' % (100 * torch.sum(y_test==predicted).double() / len(y_test)))

tensor([ 4,  5, 11, 11,  0, 11,  4,  0,  8,  5])
Accuracy of the network 98.7963 %


In [17]:
X_train = torch.tensor(X_train, dtype=torch.float)
y_train= torch.tensor(y_train, dtype=torch.long)
net.eval()
out = net(X_train)
_, predicted = torch.max(out.data, 1)
print(predicted[0:10])
#get accuration
print('Accuracy of the network %.4f %%' % (100 * torch.sum(y_train==predicted).double() / len(y_train)))

tensor([11,  0, 10,  6, 11,  1,  5,  3,  2,  5])
Accuracy of the network 99.8016 %


D:\ana\envs\packt_torch\lib\site-packages\ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.
D:\ana\envs\packt_torch\lib\site-packages\ipykernel_launcher.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  
